[package]
name = "rustlerbenchmark_math"
version = "0.1.0"
authors = []
edition = "2018"

[lib]
name = "rustlerbenchmark_math"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.26.0"
