version: "3.8"

services:
  app:
    build:
      context: .
      target: base
    container_name: rustler_benchmark_web
    command: mix phx.server
    restart: unless-stopped
    ports:
      - 4000:4000
    volumes:
      - .:/rustler_benchmark